### ISSUE TITLE
--with-* pattern is confusing on Windows

### ISSUE THREAD

**Issue by saraedum** [Normaliz/Normaliz#343]
The pattern to deduce `LDFLAGS` and `CPPFLAGS` from the value of the `--with-nauty=PREFIX` and such is imho confusing.

I don't think it's safe to assume that include files live in PREFIX/include and shared libraries in PREFIX/lib. This is certainly not the case on Windows: https://github.com/conda-forge/normaliz-feedstock/pull/20#issuecomment-634634708.

Isn't it more standard to just request LDFLAGS and CPPFLAGS to be set with the correct search paths instead and use --with and --without to enable/disable use of an external package?

**Comment by fingolfin** [comment]
No, I don't think that's "more standard". The current behavior is pretty mich the norm. Doesn't mean it can't be improved, though, possibly with a Windows specific patch. The problem for most open source projects in my experience is that even if 95% of users are on Windows, among contributors the percentage of people who
know what is "right" for Windows tends to be close or equal to zero...

Anyway, adding non-existing include and library paths should be a no-op and safe. The problem here seems to be the unconditional addition of an -rpath flag, which is problematic anyway, as it bypasses libtool. Gotta investigate that once I am at a computer (I am typing this from my phone)

**Comment by saraedum** [comment]
> Anyway, adding non-existing include and library paths should be a no-op and safe. The problem here seems to be the unconditional addition of an -rpath flag, which is problematic anyway, as it bypasses libtool.

Indeed. Why was that added?

**Comment by fingolfin** [comment]
I can only guess; when I rewrote configure.ac last year, I copied that from the old script. So I can only guess. For now, I made https://github.com/Normaliz/Normaliz/pull/345 as an experiment. Of course one can just add an `if PATH exists then SET VAR fi` into the code, but as always it's better to understand what's going on properly.

**Comment by fingolfin** [comment]
@saraedum better now?

**Comment by w-bruns** [comment]
Not clear to me what the situation is in regard to this issue. Please comment.

**Comment by fingolfin** [comment]
I believe the issue is resolved, but it would of course be great if @saraedum could confirm that (or, if it is not resolved, let us know what error they now get, so we can investigate that)
