### ISSUE TITLE
Next build failure on ubuntu-trusty

### ISSUE THREAD

**Issue by mkoeppe** [Normaliz/Normaliz#355]
Follow up from #346 and https://github.com/Normaliz/Normaliz/pull/350#issuecomment-655507396, where I reported it earlier.

As can be seen in recent runs of the new testsuite, `ubuntu-trusty` builds fail https://github.com/Normaliz/Normaliz/runs/937522109
```
/usr/bin/ld: /sage/local/lib/libnauty.a(naugraph.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/sage/local/lib/libnauty.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[3]: *** [libnormaliz.la] Error 1
```

This is with nauty from sage, which is just upstream 2.7r1 and compiling it with `-fPIC`. This works for all platforms but not for `ubuntu-trusty` and similarly old platforms.

Because Normaliz uses the same approach for installing nauty in its own `install_nmz...` scripts, I suspect that it will fail in the same way. Haven't tried; I won't touch these scripts.

(For Sage, as noted elsewhere, I am preparing a version of nauty with a proper build system in order to fix this problem. So for Sage I don't need any change in Normaliz.)

**Comment by w-bruns** [comment]
For quite a long time Normaliz used trusty as its Linux Version on Travis. We can simply try again and see what happens.

I will make a branch “trusty” for Normaliz tomorrow.

**Comment by w-bruns** [comment]
I just tried with trusty (earlier than I thought). However, I get into trouble since we are asking for libomp-dev in .travis.yml which does not exist in trusty, according to Travis.

**Comment by w-bruns** [comment]
libomp-dev-dev removed. It is only needed for OpenMP with clang.

I am testing this in the obsolete branch unification_renf of Normaliz with trusty. Please have a look at Travis build 1226.4. It seems that nauty is installled correctly. 

Builds that ask for Flint fail since it is not available from Travis under trusty. Tomorrow I will activate the Normaliz install script. Then we get a more complete picture.

**Comment by w-bruns** [comment]
Success! See

https://travis-ci.org/github/Normaliz/Normaliz/builds/714392866

Under Linux only the clang build with OpenMP failed, as expected since libomp-dev is not available. 

Compared to the current master the following changes were done:

1) Explicit installation of MPFR and Flint
2) An older version of CoCoALib that does not insist in C++ 14.

The anuty version is 27rc5.

Question for the Sage builds: is it clear that -fPIC reaches the compiler?

**Comment by mkoeppe** [comment]
Thanks for testing! 
This seems to be a static build:
```
configure --prefix=/home/travis/build/Normaliz/Normaliz/local --with-nauty --with-flint --with-e-antic --with-cocoalib --disable-shared
...
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
```
The problem that I have is with the shared library build of Normaliz (which is then used for PyNormaliz).

> Question for the Sage builds: is it clear that -fPIC reaches the compiler?

Yes, I checked this, and it also works correctly on all other Linux platforms.

**Comment by w-bruns** [comment]
Sorry. I had overlooked these lines in .travis-build.sh. I am running the tests again without them.

**Comment by w-bruns** [comment]
Have a look at

https://travis-ci.org/github/Normaliz/Normaliz/builds/714418938

The gcc builds go through. The clang build fails because of a strange problem with maxsimplex. I am not sure what would happen with a newer Linux version.

I will change .travis-buil.sh so that it mixes static and shared builds in the future.

**Comment by w-bruns** [comment]
By the way, also CoCoALib can only be built statically.

**Comment by mkoeppe** [comment]
Hm... very strange. I notice that you are using the release candidate nauty27rc5. Could it be that nauty27r1 introduced a new problem here?

**Comment by w-bruns** [comment]
Test with 27rc1 is running.

**Comment by w-bruns** [comment]
No change compared to 27rc5. See

https://travis-ci.org/github/Normaliz/Normaliz/builds/714617505

It is somewhat suspicious that the clang build with NOOPENMP does not go through, also because of a linker problem.

**Comment by fingolfin** [comment]
This is the linker error:
```
/usr/bin/ld: .libs/normaliz: hidden symbol `atexit' in /usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [normaliz] Error 1
/bin/bash ../libtool  --tag=CXX   --mode=link clang++ -std=gnu++14 -Wall -pedantic -Wno-unknown-pragmas -Wno-sign-compare  --coverage -O2 -g  -L/home/travis/build/Normaliz/Normaliz/local/lib --coverage   -o dynamic/dynamic dynamic/dynamic.o libnormaliz.la    -lnauty -lgmpxx -lgmp
/usr/bin/ld: maxsimplex/.libs/maxsimplex: hidden symbol `atexit' in /usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [maxsimplex/maxsimplex] Error 1
```

Indeed, `atexit` is not safe to be used in libraries. And Normaliz doesn't use it -- rather, this is being inserted by the compiler because of (1) `--coverage` and (2) a bug in that compiler. This is (one of) the reasons why we switched away from testing with Trusty.

I would recommend to keep testing with a more recent Ubuntu version; and just to add 1-2 separate Travis jobs using Trusty, where coverage computation is disabled.

**Comment by w-bruns** [comment]
In a few days I will change the Travis scripts so that the tests are a little more varied and a trusty test is included.

**Comment by w-bruns** [comment]
trusty not available in GitHub actions. So we close this issue.
