### ISSUE TITLE
Define a monoid from list of generators

### ISSUE THREAD

**Issue by thchr** [Normaliz/Normaliz#372]
I apologize in advance for asking what is at least in significant part a question here. I've been poring over the documentation for a good while now, and I haven't been able to find an answer - so I've finally turned to create this issue.

**Problem**
In short, from reading the documentation, I could not figure out how to set up a calculation for an affine monoid from a set of generators alone. (I've had a great time using Normaliz via the `inequalities` and `cone` input type earlier though!)

**Motivation**
My specific motivation is that I have a situation where I know that a monoid `M` is generated by a set of elements `{xᵢ}`, i.e. that

```M = {a₁x₁ + a₂x₂ + ... + aₙxₙ : aᵢ ∈ ℤ₊}```

and I am interested in establishing whether these elements are also a Hilbert basis for `M` (i.e., whether they are all irreducible). My idea then was to set up `M` in Normaliz, calculate its Hilbert basis, and compare back against `{xᵢ}`.

I tried the `cone_and_lattice` input, but realized that probably wasn't wholly appropriate (e.g. if I give `cone_and_lattice` the `xᵢ` elements, the computed Hilbert basis occasionally has *more* elements that `{xᵢ}`).

I suspect my problems mainly reflect a lack of mathematical background and an associated inability to follow some documentation fully - but I'm wondering if it would be worthwhile to give a simple explanation in the documentation of how to achieve this for non-specialists from other fields.
[E.g., the very first line of [Usage of Normaliz](https://www.normaliz.uni-osnabrueck.de/home/use-of-normaliz/) indicates that Normaliz will happily take a list of generators as input - but it is then less clear how to achieve that exactly in the documentation]

Thanks!

**Comment by w-bruns** [comment]
Normaliz can't compute Hilbert bases of arbitrary affine monoids. Its monoids must be the intersection of a rational cone C embedded in some real vector space of finite dimension and a sublattice L of the lattice of all integral vectors in that space (we assume that a basis of the space has been fixed).  If C is pointed, then the minimal system of generators of our monoid is uniquely determined. If the cone is not pointed, then Normaliz passes to the pointed quotient of C and the corresponding quotient of L. There are various ways to define C and L.

Do you want to compute a minimal system of generators of an affine monoid in general?

**Comment by thchr** [comment]
Ah, I see - I had thought it might be possible to define the monoid just from some (possibly overcomplete) set of generators alone. 

My aim indeed was to compute a minimal system of generators for the associated affine monoid (or, just to check whether the provided generators were a minimal set).

In my case, the lattice that the generators would build (i.e., the integer combinations of `{xᵢ}`) would include points that I know are not in the monoid - some combinations of additions of subtractions - so I am not able to use these generators immediately to infer the associated lattice, as far as I can see. I do know that the associated cone is pointed though.

**Comment by pedritomelenas** [comment]
You may use the [gap](https://www.gap-system.org/) package [numericalsgps](https://gap-packages.github.io/numericalsgps/). This package may benefit from normaliz through [normalizinterface](https://gap-packages.github.io/NormalizInterface/).

**Comment by w-bruns** [comment]
Now contained in 3.10.0.

**Comment by w-bruns** [comment]
First an input file:

```
amb_space 3
monoid 6
1 0 0
2 3 5
0 0 1
1 1 2
0 1 3
3 1 0
/* grading 1 -2 1*/
/*HilbertSeries*/
/*GroebnerBasis*/
/*Lex*/
/*MarkovBasis*/
/*gb_degree_bound 11*/
/*gb_min_degree 9*/
/*Multiplicity*/
/*SingularLocus*/
/*CodimSingularLocus*/
/*IsSerreR1*/
```

You can activate the commented out computation goals and run the file. The computation goals `HilbertBasis` and `IsIntegrallyCtlosed` are always computed, and therefore not in the list. The degree bounds make only sense with `GroebnerBasis` or` MarkovBasis`. The default monomial order for `GroebnerBasis` is deg revlex. You can ask for `Lex` and `DegLe`. `GroebnerBasis` and `MarkovBasis` are written to extra files with suffixes `grb` and `mrk`, resp. The default grading is the standard grading that gives degree 1 to every basis vector.

For the C++ intefrace one has the new input type `monoid`, for example

Cone\<long long\> M(Type::monoid, Gens)

where Gens is a matrix containing the generators. Otherwise there is not much to say, except that the computation goals shown in the input file above have been added, except `HiilbertSeriesd` and `Multiplicity` that existed already.

The essential point is that te computations are done for the monoid and **not** for the integral closure in some lattice.
