### ISSUE TITLE
omp_get_level not implemented in pthreads-win32

### ISSUE THREAD

**Issue by isuruf** [Normaliz/Normaliz#376]
For windows we are using pthreads-win32 and it doesn't support `omp_get_level`

**Comment by isuruf** [comment]
Nvm, I'm confusing openmp and pthreads

**Comment by w-bruns** [comment]
I would like to have your advice on the compilation of a MS Windows binary. So far we have been using the Intel compiler within Visual Studio. That is absolutely o.k., and sometimes reveals weak points in the code that are not noticed by g++ or clang++. The disadvantage is that we need a license for the Intel compiler and that the procedure via Visual Studio is disjoint from the configure-make-make install cycle. 

Cygwin is not a good alternative since it does not allow OpenMP. Perhaps MinGW would be better, but we haven't tried it yet.

How do you compile the Windows binaries?  

Winfried

**Comment by isuruf** [comment]
I compile it using Clang targeting Visual Studio. I use bash, make, coreutils from msys2 project to run configure and make.

**Comment by w-bruns** [comment]
Thanks! I have found

https://clang.llvm.org/get_started.html

It should be helpful.
