### ISSUE TITLE
MacOS binary or compilation

### ISSUE THREAD

**Issue by MathieuDutSik** [Normaliz/Normaliz#392]
Normaliz compiles perfectly for Linux. But on MacOS, this is another story.
First, it is not available via **brew install normaliz** as one would hope.

Then the **./configure** does not work because of missing gmp.
Adding the prefix with a brew installed gmp with **--with-gmp=/usr/local**.

So, it seems that normaliz does not compile on Mac, maybe because of
incorrect configure script.

**Comment by fingolfin** [comment]
Of course it compiles on macOS. Our CI compile it there on every commit. Many people compile it there without problems. I compile it there regularly without problems, too. I notice that you have not listed an actual build error either?

The `configure` script has `--with-gmp` etc. options precisely so that one can point it at installations of GMP etc. which are outside of `/usr`, as is the "standard" for configure scripts. You already found it, too. Yet you still say "it does not compile on Mac". So I assume you are (still) getting some error? But which? Your message does not mention it.

Regarding homebrew: of course it would be nice if normaliz was available there. But for that, "someone" would have to package it. But note that Homebrew explicitly frowns upon software authors to submit and maintain recipes for their own software. They want 3rd parties to provide these. Maybe you are interested?

**Comment by MathieuDutSik** [comment]
Thank you Max for prompt answer!
The error I obtained is
```
checking size of long long... 8
checking gmpxx.h usability... yes
checking gmpxx.h presence... yes
checking for gmpxx.h... yes
checking for __gmpz_init in -lgmpxx... no
configure: error: GMP C++ library not found. Make sure it was compiled with --enable-cxx
```

So, it is not read correctly for mysterious reasons since the gmp install works fine for many other programs.

Regarding Homebrew, it is strange that they frown on that. But yes I would be fine to write the recipe.

**Comment by w-bruns** [comment]
Let me add to Max's comment that in our CI for Mac there is one build that explicitly uses the install scripts.

We had a problem which, I think, is still contained in version 3.9.2, namely the placement of

```
CPPFLAGS="$CPPFLAGS $GMP_CPPFLAGS"
LDFLAGS="$LDFLAGS $GMP_LDFLAGS"
```
in `configure.ac`. It must precede the `AX_CHECK_LIBRARY` for GMP, as it does in the current `configure.ac` of the master branch. This bug was an obstruction to an explicit `--with-gmp` if `configure` was run **separately**. This could explain your problem.

In the installation scripts, `CPPFLAGS` and `LDFLAGS` are set according to  `GMP_INSTALLDIR`. For MacOS, `GMP_INSTALLDIR` is set to `/usr/local`.

**Comment by fingolfin** [comment]
@MathieuDutSik can you test if `master` branch compiles? If so, perhaps @w-bruns can make a 3.9.3 release with that fix? (if/once he has time, of course -- it's Easter weekend :-)

**Comment by w-bruns** [comment]
We are close to 3.9.3. I will release it next week. Thanks for your willingness to help us with homebrew.

Have a look at https://github.com/Normaliz/Normaliz/issues/246.

**Comment by mahrud** [comment]
Normaliz is available via brew, but on a third party "tap". Try the following:
```
brew install Macaulay2/tap/normaliz
```

**Comment by w-bruns** [comment]
v3.9.3 has been released:

https://github.com/Normaliz/Normaliz/releases
