### ISSUE TITLE
3.0.0 or 3.0.90 in Sage?

### ISSUE THREAD

**Issue by dimpase** [Normaliz/Normaliz#83]
We'd like to do a (long overdue) update of normaliz in Sage.
http://trac.sagemath.org/ticket/18708
Should we use 3.0.0, or 3.0.90?

**Comment by w-bruns** [comment]
Dear Dmitrii,

I assume you are talking about the package originally set up by Andrei 
Novoseltsev.

I think we will publish 3.1 at the end of January 2016. If you can wait 
for it, please base the update on it. If you want to do the update now, 
please take 3.0.90. We have corrected very minor one bug.

One of the main issues for the near future is updating and taking care 
of the Normaliz interfaces. Since I do not know Sage, it is unclear to 
me how to use Normaliz within Sage. Only via Macaulay 2 or Singular? Or 
is there a more direct way? The access from Macaulay 2 or Singular is 
via the exchange of files. On the other hand, Normaliz has an C++ API 
(needs better documentation) that is used in CoCoA and GAP.

Two questions: Should we have an interface that allows direct access 
from Sage without intermediate packages ? If so, should it be based on 
file exchange or should it be based on direct access via the API?

Sincerely,

Winfried

Am 20.12.2015 um 21:52 schrieb Dmitrii Pasechnik:
>
> We'd like to do a (long overdue) update of normaliz in Sage.
> http://trac.sagemath.org/ticket/18708
> Should we use 3.0.0, or 3.0.90?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/83>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by dimpase** [comment]
Dear Winfried,
we can certainly wait till the end of January, there is no rush. A new release of Sage has just appeared, so the next one won't happen before Fer or Mar.

Indeed, the only way I know about using Normaliz in Sage is from Singular. 
Indeed, it should be possible to create an interface to Normaliz to Sage/Python, using
Cython (this is a standard way to interface C/C++ libraries from Sage --- another one is via
pexpect (i.e. pipes/files), but the latter is slow and not very stable).
We can also think about interfacing via GAP (more precisely via libGAP).

Perhaps I can get a student to work on this --- what would you think about?

Dima

**Comment by w-bruns** [comment]
Dear Dima,

it would be great if you could have a student working on a Sage/Normaliz 
interface.

As mentioned already, a better documentation of libnormaliz is on the 
agenda, and I am quite sure that it will be inclzded in 3.1.

Merry Christmas (now or on January 7) and a Happy New Year!

Winfried

Am 21.12.2015 um 13:03 schrieb Dmitrii Pasechnik:
>
> Dear Winfried,
> we can certainly wait till the end of January, there is no rush. A new 
> release of Sage has just appeared, so the next one won't happen before 
> Fer or Mar.
>
> Indeed, the only way I know about using Normaliz in Sage is from 
> Singular.
> Indeed, it should be possible to create an interface to Normaliz to 
> Sage/Python, using
> Cython (this is a standard way to interface C/C++ libraries from Sage 
> --- another one is via
> pexpect (i.e. pipes/files), but the latter is slow and not very stable).
> We can also think about interfacing via GAP (more precisely via libGAP).
>
> Perhaps I can get a student to work on this --- what would you think 
> about?
>
> Dima
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/83#issuecomment-166284991>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by dimpase** [comment]
Season's greetings!

(given the season, ourselves we are not able to decide between https://en.wikipedia.org/wiki/Hanukkah and https://en.wikipedia.org/wiki/Flying_Spaghetti_Monster  :-))

**Comment by w-bruns** [comment]
Dear Dima,

version 3.1 will be made public on Monday.

Can we add you to our mailing list?

Winfried

Am 21.12.2015 um 13:03 schrieb Dmitrii Pasechnik:
>
> Dear Winfried,
> we can certainly wait till the end of January, there is no rush. A new 
> release of Sage has just appeared, so the next one won't happen before 
> Fer or Mar.
>
> Indeed, the only way I know about using Normaliz in Sage is from 
> Singular.
> Indeed, it should be possible to create an interface to Normaliz to 
> Sage/Python, using
> Cython (this is a standard way to interface C/C++ libraries from Sage 
> --- another one is via
> pexpect (i.e. pipes/files), but the latter is slow and not very stable).
> We can also think about interfacing via GAP (more precisely via libGAP).
>
> Perhaps I can get a student to work on this --- what would you think 
> about?
>
> Dima
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/83#issuecomment-166284991>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by dimpase** [comment]
Thanks!
Yes, please add me to the list.
Dima
