### ISSUE TITLE
New input type subspace?

### ISSUE THREAD

**Issue by csoeger** [Normaliz/Normaliz#86]
Could be useful for input from polymake.

**Comment by w-bruns** [comment]
Weshalb nicht, aber was beinhaltet er?

Winfried

Am 30.01.2016 um 11:39 schrieb Christof Soeger:
>
> Could be useful for input from polymake.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/86>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by w-bruns** [comment]
Könnte es ein, dass subspace = saturation? Wäre vielleicht ein besserer 
Name.

Winfried

Am 30.01.2016 um 11:39 schrieb Christof Soeger:
>
> Could be useful for input from polymake.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/86>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by csoeger** [comment]
It should contain a basis of a linear subspace. I suggested subspace because the matching cone property and getters to this are named MaximalSubspace.
polymake currently uses libnormaliz only for pointed cones. When they already know it is not pointed and now would like to use the only input possibility would be to add the generators of the linearity space and their negatives. We then would start computing, find out that the cone is not pointed and restart. This could be avoided with the new input type.
It will require some work on how we internally use the two SublatticeRepresentations.

**Comment by w-bruns** [comment]
O.K. I understand. It is not the same as saturation, which means that we 
intersect with a subspace.

We want to prepare the nonpointed situation nicely. So we would 
immediately pass to the quotient modulo the input subspace (and perhaps 
to a further quotient if we have not yet reached a pointed cone).

I think that we then need 3 SLRs. BasisChange, BasisChangePerhapsPointed 
(new) and BasisChangePointed. One could compute "Perhaps" at the end of 
the constructor.

But I think there is a simpler way, at least temporarily. We ourselves 
add the sum of the negatives (enough to generate the group as a monoid) 
and directly compute BasisChanePointed via the support hyperplanes 
instead of starting compute() for the full_cone.

Winfried

Am 30.01.2016 um 18:57 schrieb Christof Soeger:
>
> It should contain a basis of a linear subspace. I suggested subspace 
> because the matching cone property and getters to this are named 
> MaximalSubspace.
> polymake currently uses libnormaliz only for pointed cones. When they 
> already know it is not pointed and now would like to use the only 
> input possibility would be to add the generators of the linearity 
> space and their negatives. We then would start computing, find out 
> that the cone is not pointed and restart. This could be avoided with 
> the new input type.
> It will require some work on how we internally use the two 
> SublatticeRepresentations.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/86#issuecomment-177261581>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by csoeger** [comment]
We should include the input type and this easy way in 3.1. A better internal handling can then come later.
Is `subspace` a good name?

**Comment by w-bruns** [comment]
I agree.

We could do the following:

1) Interpretation of the input "subspace": if there is a matrix of type 
"cone", the vectors in subspace and the sum of their negatives are 
appended to "cone". Similarly if there is a matrix of type 
"cone_and_lattice". (This saves us a "and_lattice" variant of "subspace".).

What to do if we have neither "cone" nor" cone_and_lattice"? Two 
possibilities: BadInputException or interpretation as "cone".

2) Computation: We simply add "IsPointed" as an explicit computation 
goal. This possibility exists already and makes full_cone to check 
pointedness first.

Alternative to 2): We compute BasisChangePointed from the subspace 
generators at the end of the constructor instead of simply setting it 
equal to BasisChange. More risky, but I think it would work! If we never 
assume in the compute functions that BasisChange=BasisChangePointed, it 
should be no problem. In this case it can of course happen that we must 
restart the computation if the vectors in "subspace" do not generate the 
maximal subspace.

A not so nice varaiant of 2) would be to assume that the cone modulo the 
subspace is pointed and to throw a BadInputException if it is not.

Winfried

Am 30.01.2016 um 20:49 schrieb Christof Soeger:
>
> We should include the input type and this easy way in 3.1. A better 
> internal handling can then come later.
> Is |subspace| a good name?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/86#issuecomment-177284533>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by w-bruns** [comment]
Done.
